// Generated by CoffeeScript 1.6.3
(function() {
  var Employee, Person, patrick, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Person = (function() {
    function Person(name) {
      this.name = name;
    }

    Person.prototype.drink = function(n) {
      return console.log(this.name + (" drank " + n + " cups"));
    };

    return Person;

  })();

  Employee = (function(_super) {
    __extends(Employee, _super);

    function Employee() {
      _ref = Employee.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Employee.prototype.drink = function(n) {
      Employee.__super__.drink.call(this, 10);
      return console.log(" of coffee");
    };

    return Employee;

  })(Person);

  patrick = new Employee("Patrick Simpson");

  patrick.drink();

}).call(this);

/*
//@ sourceMappingURL=classes-1.map
*/
