// Generated by CoffeeScript 1.6.3
(function() {
  var patrick;

  patrick = {
    name: "Patrick Simpson",
    age: 28,
    awesome: true,
    skills: ["JavaScript", "CoffeeScript", "Bacon"]
  };

  console.log(patrick.name);

}).call(this);

/*
//@ sourceMappingURL=objects-1.map
*/
