// Generated by CoffeeScript 1.6.3
(function() {
  if (!true) {
    "Panic";
  }

  if (!true) {
    "Panic";
  }

  if (true === 1 && 1 !== 2) {
    "Fail";
  }

  if (true !== true || false !== false) {
    "Nope";
  }

}).call(this);

/*
//@ sourceMappingURL=logic-1.map
*/
