// Generated by CoffeeScript 1.6.3
(function() {
  var modNames, names, prettyPrint;

  names = ["Patrick", "Joe", "Smoe", "Barney", "Batman"];

  prettyPrint = function(string) {
    return console.log("~~~ " + string + " ~~~");
  };

  modNames = names.map(function(name) {
    if (name === "Patrick") {
      prettyPrint(name);
      name = "Patrick Simpson";
    }
    return name;
  });

  console.log(names);

  console.log(modNames);

}).call(this);

/*
//@ sourceMappingURL=loops-2.map
*/
