// Generated by CoffeeScript 1.6.3
(function() {
  var me, name, names, _i, _j, _len, _len1;

  names = ["Patrick", "Joe", "Smoe", "Barney", "Batman"];

  for (_i = 0, _len = names.length; _i < _len; _i++) {
    name = names[_i];
    prettyPrint(name);
  }

  me = (function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = names.length; _j < _len1; _j++) {
      name = names[_j];
      if (name === "Patrick") {
        _results.push(name);
      }
    }
    return _results;
  })();

  for (_j = 0, _len1 = names.length; _j < _len1; _j++) {
    name = names[_j];
    doOtherThing(name);
  }

}).call(this);

/*
//@ sourceMappingURL=loops-1.map
*/
