// Generated by CoffeeScript 1.6.3
(function() {
  var computeName, me;

  me = "Joe";

  computeName = function(name) {
    if (name === "") {
      return me;
    } else {
      return "Patrick Simpson";
    }
  };

}).call(this);

/*
//@ sourceMappingURL=scoping-1.map
*/
