// Generated by CoffeeScript 1.6.3
(function() {
  var computeName, me;

  me = "";

  computeName = function() {
    me = "Patrick Simpson";
    return me;
  };

}).call(this);

/*
//@ sourceMappingURL=scoping-2.map
*/
