// Generated by CoffeeScript 1.6.3
(function() {
  var people,
    _this = this;

  people = ["Patrick", "Joe", "Smoe", "Barney", "Batman"];

  people.map(function(person) {
    _this.people;
    return console.log(person);
  });

}).call(this);

/*
//@ sourceMappingURL=fatarrow.map
*/
