// Generated by CoffeeScript 1.6.3
(function() {
  var computeName;

  computeName = function() {
    var me;
    me = "Patrick Simpson";
    return me;
  };

}).call(this);

/*
//@ sourceMappingURL=functions-1.map
*/
