// Generated by CoffeeScript 1.6.3
(function() {
  var calculate, worker;

  calculate = function(a, b) {
    if (b < 1) {
      return (a * (a + 1)) + 1;
    } else {
      if (a < 1) {
        return -1 * b;
      }
    }
    return (a / b) * (a + b);
  };

  worker = function() {
    var result;
    result = calculate(1, 2);
    console.log(result);
    result = calculate(0, 1);
    console.log(result);
    result = calculate(2, 0);
    return console.log(result);
  };

}).call(this);

/*
//@ sourceMappingURL=functions-2.map
*/
