// Generated by CoffeeScript 1.6.3
(function() {
  var bio, html, name;

  name = "Patrick";

  bio = "From Dayton Ohio Married with 3 children. Loves Coffee, and drinks it too.";

  html = "<p>\n  " + name + " had a cup of coffee\n</p>";

}).call(this);

/*
//@ sourceMappingURL=strings-1.map
*/
